# Generated by Django 5.2 on 2025-04-23 19:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Developer'), (3, 'Reviewer'), (4, 'Translator')]), default=4, max_length=3, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('main_language', models.CharField(max_length=2)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Create Key'), (2, 'Delete Key'), (3, 'Edit Key'), (4, 'Import Keys'), (5, 'Edit Translation'), (6, 'Review Translation')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
