# Generated by Django 5.2 on 2025-04-24 07:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Developer'), (3, 'Reviewer'), (4, 'Translator')]), default=list, max_length=3, size=None),
        ),
    ]
