# Generated by Django 5.2 on 2025-04-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='languages',
            field=models.JSONField(),
        ),
    ]
