# Generated by Django 5.2 on 2025-04-10 11:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_languages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collaborator',
            unique_together={('user', 'project', 'role')},
        ),
    ]
