# Generated by Django 5.2 on 2025-05-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_languages_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='count',
            new_name='translation_count',
        ),
        migrations.AddField(
            model_name='language',
            name='reviewed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='language',
            unique_together={('code', 'project')},
        ),
    ]
