services:
  db:
    container_name: i18nizelydb
    image: postgres:17
    environment:
      - POSTGRES_DB=i18nizely
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432