# Generated by Django 5.2.1 on 2025-05-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contexts/'),
        ),
    ]
