# Generated by Django 5.2 on 2025-04-11 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0002_initial'),
        ('projects', '0004_alter_collaborator_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='key',
            unique_together={('name', 'project')},
        ),
    ]
